import random
import string
from typing import Dict, Any

EMAIL_DOMAINS = [
    'testmail.com', 'example.org', 'qa-demo.net', 'fake.co'
]
NAME_CHARS = string.ascii_letters + string.digits + '_'
NUMBERS = string.digits

def get_random_int(min_val: int, max_val: int) -> int:
    """
    Utility function to get a random integer between min and max (inclusive).
    """
    return random.randint(min_val, max_val)

class DataGenerator:
    """
    A lightweight utility class mimicking core functionalities of a library like Lodash,
    primarily focused on generating random data for testing purposes.
    """

    def generate_random_string(self, length: int, chars: str) -> str:
        """
        Generates a random string of a specified length using the defined character set.
        """
        return ''.join(random.choice(chars) for _ in range(length))

    def get_random_phone_number(self) -> str:
        """
        Generates a random 10-digit phone number in a common format: (XXX) XXX-XXXX.
        """
        area_code = str(get_random_int(200, 999))
        prefix = str(get_random_int(100, 999))
        line_number = str(get_random_int(1000, 9999))
        return f"({area_code}) {prefix}-{line_number}"

    def get_random_first_name(self) -> str:
        """
        Generates a random string suitable for a first name (6-12 characters).
        """
        length = get_random_int(6, 12)
        random_string = self.generate_random_string(length, NAME_CHARS)
        return random_string.capitalize()

    def get_random_last_name(self) -> str:
        """
        Generates a random string suitable for a last name (6-12 characters).
        """
        length = get_random_int(6, 12)
        random_string = self.generate_random_string(length, NAME_CHARS)
        return random_string.capitalize()
    
    def get_random_postal_code(self) -> str:
        """
        Generates a random 5-digit postal code (suitable for many regions).
        """
        return str(get_random_int(10000, 99999))

    def get_random_email(self, user_name: str) -> str:
        """
        Generates a random email address using the provided username and a random domain.
        """
        domain = random.choice(EMAIL_DOMAINS)
        return f"{user_name}@{domain}"

    def get_random_user(self, user_role: str) -> Dict[str, Any]:
        """
        Generates a full random user object ready for insertion into the database.
        Returns a dictionary omitting the _id field, as it is generated by MongoDB.
        """
        first_name = self.get_random_first_name()
        last_name = self.get_random_last_name()
        username_suffix = self.generate_random_string(4, NUMBERS)
        username = f"{first_name.lower()}.{last_name.lower()}_{username_suffix}" 

        new_user: Dict[str, Any] = {
            "username": username,
            "role": user_role,
            "firstName": first_name,
            "lastName": last_name,
            "postalCode": self.get_random_postal_code(),
            "isDeleted": False,
            "isVisible": True,
            "email": self.get_random_email(username),
            "phone": self.get_random_phone_number(), 
        }
        return new_user

_ = DataGenerator()
